version: '3.8'

services:
  faxing-frontend:
    container_name: faxing-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - faxing-backend

  faxing-backend:
    container_name: faxing-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./results:/results
    environment:
      - NODE_ENV=development
      - PORT=8081 